trusted_idps:
  - issuer: https://iam.cloud.infn.it/
    group_claim: groups
    user_groups:
      - name: test
        slas:
          - doc_uuid: c2bb880f0aa443a49abcbbbe2e96b48b
            start_date: 2023-10-11
            end_date: 2023-10-25

openstack:
  - name: cloud-veneto
    status: maintenance
    auth_url: https://keystone-cv.pd.infn.it/v3
    identity_providers:
      - name: infn-cc
        protocol: openid
        endpoint: https://iam.cloud.infn.it/
    projects:
      - id: 511e6aa1fdb54ef7bca634fa1038a2a2
        sla: c2bb880f0aa443a49abcbbbe2e96b48b
        default_public_net: INFN-WAN
        default_private_net: ML-INFN-wan
